# This is a set of bugbot commands for issues and merge requests - setting any of the
# bugbot::foo labels will trigger gitlab-triage to run with this ruleset (well, the
# one we have on the main branch at the time)
#
# Note that for adding labels, the label must first created in the project.

# Re-used in issues and mrs
.close_needinfo: &close_needinfo
  name: "Close stale needinfo bugs"
  conditions:
    labels:
      - "bugbot::needinfo-timeout"
  actions:
    remove_labels:
      - "bugbot::needinfo-timeout"
    comment: |
      I'm closing this bug because some information we requested a while ago was never supplied and
      we're not able to continue without this information.
      Please feel free to re-open.
    status: "close"

.remind_needinfo: &remind_needinfo
  name: "Remind users of needinfo bugs"
  conditions:
    labels:
      - "bugbot::needinfo-reminder"
  actions:
    labels:
      - "waiting on reporter"
    remove_labels:
      - "bugbot::needinfo-reminder"
    comment: |
      Hi. This is a friendly reminder that the maintainers are waiting on some information by
      you (or maybe someone cc'd on this bug). If the information is not provided we may not
      be able to proceed with this issue or merge request. Please check the recent comments, thanks.

.help_needed: &help_needed
  name: "Remind users help is needed"
  conditions:
    labels:
      - "bugbot::help-needed"
  actions:
    labels:
      - "help needed"
    remove_labels:
      - "bugbot::help-needed"
    comment: |
      Hi. This issue or merge request needs help. This simply means that for
      the foreseeable future, the maintainers will not have time to work on
      this.

      If this is a request for a new feature, then the feature is unlikely to
      be implemented unless you or another contributor files a merge request.
      If a merge request already exists maybe it needs finishing which often
      involves adding documentation or tests.

      If this is an issue affecting a specific device then it is unlikely to be
      fixed. This may be because it requires specific hardware to reproduce or
      it may be that the use case is niche enough that the maintainers do not
      have time to implement it.

      In short, to resolve this issue or get this merge request into udev-hid-bpf
      help is needed.

resource_rules:
  issues:
    rules:
      - name: "Request hid-recorder output"
        conditions:
          labels:
            - "bugbot::hid-recorder"
        actions:
          remove_labels:
            - "bugbot::hid-recorder"
          comment: |
            Looks like we may need some extra information that isn't yet available in this issue.
            Please **attach** (do not paste) the output of [`hid-recorder`](https://github.com/hidutils/hid-recorder/)
            for this device (run `sudo hid-recorder` without argument and it will let you pick the device).
            This should show the data the kernel receives from the device and may provide a hint on what's going on here.
      - name: "Expect a merge request"
        conditions:
          labels:
            - "bugbot::expect-mr"
        actions:
          remove_labels:
            - "bugbot::expect-mr"
          comment: |
            I'm closing this bug in anticipation of a merge request that fixes this issue.

            If you are a new contributor, please see
            [the freedesktop.org wiki](https://gitlab.freedesktop.org/freedesktop/freedesktop/-/wikis/home)
            on how to get permissions to fork a project and file a merge request.
          status: "close"
      - *close_needinfo
      - *remind_needinfo
      - *help_needed
  merge_requests:
    rules:
      - name: "Remind contributor of commit rules"
        conditions:
          labels:
            - "bugbot::commit-rules"
        actions:
          remove_labels:
            - "bugbot::commit-rules"
          comment: |
            Hi. Looks like the pipeline failed because one or more of the commits in this MR do not meet our requirements.
            Most commonly this the format of the commit message itself. The "Test summary" above has the details.

            Most commonly the issue is a missing `Signed-off-by` tag in the commit message.

            Please see [libinput's docs for submitting code](https://wayland.freedesktop.org/libinput/doc/latest/contributing.html#submitting-code)
            that explain how to amend and force-push to this repo. These docs work well for udev-hid-bpf as well.
      - name: "Remind contributor that info needs to be in commit messages"
        conditions:
          labels:
            - "bugbot::info-in-commit-message"
        actions:
          remove_labels:
            - "bugbot::info-in-commit-message"
          comment: |
            Hi. Thanks for the merge request. I'm here to request that you add
            some documentation about this merge request to the
            **commit message** (or messages). You may have already written some
            in the merge request description and in many cases it's fine to
            copy/paste that into the commit message(s).

            The reason is simple: once merged, no-one really looks at this this
            page here anymore. The git log on the other hand is what developers
            will use to understand the code so the information must be quickly
            accessible via git.

            Please see [libinput's docs for submitting code](https://wayland.freedesktop.org/libinput/doc/latest/contributing.html#submitting-code)
            that explain how to amend and force-push to this repo. These docs work well for udev-hid-bpf as well.
      - *close_needinfo
      - *remind_needinfo
      - *help_needed
